# примеры API-запросов

#@baseUrl = http://127.0.0.1:8000/

# получение объявлений
GET http://127.0.0.1:8000/advertisements/
Content-Type: application/json
Authorization: Token 5e1e8d6456c76ec59dca53be9ac5f87c874c68bd
###

# создание объявления
POST http://127.0.0.1:8000/advertisements/
Content-Type: application/json
Authorization: Token 5e1e8d6456c76ec59dca53be9ac5f87c874c68bd

{
  "title": "Стол IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH http://127.0.0.1:8000/advertisements/1/
Content-Type: application/json
Authorization: Token 5e1e8d6456c76ec59dca53be9ac5f87c874c68bd

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET http://127.0.0.1:8000/advertisements/?creator=1
Content-Type: application/json
Authorization: Token 5e1e8d6456c76ec59dca53be9ac5f87c874c68bd
###

# фильтрация по дате
GET http://127.0.0.1:8000/advertisements/?created_at_before=2022-11-24
Content-Type: application/json
Authorization: Token 5e1e8d6456c76ec59dca53be9ac5f87c874c68bd

###
# удаление обьявления
DELETE http://127.0.0.1:8000/advertisements/7/
Content-Type: application/json
Authorization: Token e2e77102e583aa9182a2297389796e71375e0e3a

