# Generated by Django 4.0.6 on 2022-08-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articlescope_scope_articlescope_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='scope',
            name='name',
            field=models.CharField(default=None, max_length=50, verbose_name='Имя тега'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articlescope',
            name='scope',
            field=models.ForeignKey(on_delete=models.SET(None), related_name='tags', to='articles.scope', verbose_name='Раздел'),
        ),
    ]
