# Generated by Django 4.0.6 on 2022-08-02 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_scope_name_alter_articlescope_scope'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'verbose_name': 'Сфера', 'verbose_name_plural': 'Сферы'},
        ),
        migrations.RemoveField(
            model_name='articlescope',
            name='is_main',
        ),
        migrations.RemoveField(
            model_name='scope',
            name='scopes',
        ),
        migrations.AddField(
            model_name='article',
            name='scopes',
            field=models.ManyToManyField(related_name='scopes', through='articles.ArticleScope', to='articles.scope'),
        ),
        migrations.AddField(
            model_name='scope',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Основной'),
        ),
    ]
