# Generated by Django 4.0.6 on 2022-08-04 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0005_remove_sensor_measurements_measurement_sensors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='sensors',
        ),
        migrations.AddField(
            model_name='sensor',
            name='measurements',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensor', to='measurement.measurement', verbose_name='Измерения'),
        ),
    ]
