# Generated by Django 4.0.6 on 2022-08-05 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0007_remove_sensor_measurements_measurement_id_sensor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='ID_sensor',
            new_name='sensor',
        ),
    ]
