# Generated by Django 4.0.6 on 2022-08-06 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0009_alter_measurement_sensor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='sensor',
        ),
        migrations.AddField(
            model_name='sensor',
            name='measurements',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sensor', to='measurement.measurement', verbose_name='Измерения'),
            preserve_default=False,
        ),
    ]
