# Generated by Django 4.0.6 on 2022-08-06 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0010_remove_measurement_sensor_sensor_measurements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='measurements',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensor', to='measurement.measurement', verbose_name='Измерения'),
        ),
    ]
