# Generated by Django 4.0.6 on 2022-08-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0012_remove_sensor_measurements_measurement_measurements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='measurements',
            field=models.ManyToManyField(blank=True, related_name='measurements', to='measurement.sensor', verbose_name='Измерения'),
        ),
    ]
