# Generated by Django 4.0.6 on 2022-08-07 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0013_alter_measurement_measurements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='measurements',
        ),
        migrations.AddField(
            model_name='measurement',
            name='sensor',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='measurement.sensor', verbose_name='Измерения'),
            preserve_default=False,
        ),
    ]
